### ISSUE TITLE
Whats a roadmap of this repo?

### ISSUE THREAD

**Issue by swapnilsarwe** [mpociot/chuck-norris-jokes#2]
Just curious about the purpose of this package and would love to contribute to it any possible way.

I am a great fan of Chuck Norris Jokes and so is Maarten Decat.

We already have the api created by Maarten Decat (https://github.com/maartendecat/icndb-api), whose sole purpose is to maintain the centralised repo of Chuck Norris Jokes. It has not got any updates for a long time, but still I think he should be open for suggestions. You already using the same api in (https://github.com/botman/botman) package.

I know its just been a day since you created this repo, but as I said I am curious and a big fan of chuck norris jokes.

**Comment by mpociot** [comment]
Hello @swapnilsarwe 

This repository is currently being used as an example for my [PHP Package Development](https://phppackagedevelopment.com) video course :) 

So it's more meant to be a playground project for the course.
